#!/usr/bin/env bash

# Appends to the .bashrc
cat <<EOF >> ~/.bashrc

# wirecat specific setup start

# Use vim mode
set -o vi

# wirecat specific setup end

EOF

# Appends to the .inputrc
cat <<EOF >> ~/.inputrc

# wirecat specific setup start

set keyseq-timeout 50
set show-mode-in-prompt on

# wirecat specific setup end

EOF